# Generated by Django 3.1.7 on 2021-04-20 00:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_funcionario', models.CharField(choices=[('estoquista', 'Estoquista'), ('caixa', 'Caixa'), ('vendedor', 'Vendedor'), ('analista', 'Analista'), ('gerente', 'Gerente')], max_length=255)),
                ('telefone', models.CharField(help_text='Preencha o campo sem " ( ) " do DDD.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', message='Por favor, insira apenas os números do telefone.')])),
                ('endereco', models.CharField(max_length=300)),
                ('cpf', models.CharField(help_text='Preencha o campo apenas com números.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11,11}$', message='Por favor, não insira letras, " . " e " - " no campo abaixo.')], verbose_name='CPF')),
                ('image', models.ImageField(blank=True, default='static/img/theme/avocado.png', null=True, upload_to='controle_usuarios/media/images', verbose_name='Imagem')),
                ('data_admissao', models.DateField(auto_now_add=True, verbose_name='Admitido em')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Demitido em')),
                ('ativo', models.BooleanField(default=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['funcionario'],
            },
        ),
    ]
