# Generated by Django 3.1.7 on 2021-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='XXX.XXX.XXX-XX', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='image',
            field=models.ImageField(blank=True, default='static/img/theme/avocado.png', null=True, upload_to='controle_usuarios/media/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
