# Generated by Django 3.1.7 on 2021-05-19 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0002_regex_cpf_telegone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(help_text='Preencha o campo apenas com números.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', message='Por favor, insira apenas os números do telefone.')]),
        ),
    ]
