# Generated by Django 3.1.7 on 2021-03-20 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Total do Pedido')),
                ('descricao', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição do Pedido')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='controle_pedidos/NFE', verbose_name='Nota Fiscal Eletronica')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Pedido Realizado Em')),
                ('status', models.SmallIntegerField(choices=[(1, 'Gerado'), (2, 'Em separação'), (3, 'Enviado'), (4, 'Mecadoria Recebida'), (5, 'Concluído')], default=1, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_criadopor', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='controle_estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='CarrinhoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('pedidocompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_pedidos.pedidocompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_estoque.produto')),
            ],
        ),
    ]
