# Generated by Django 3.1.7 on 2021-03-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preço Total do Pedido')),
                ('descricao', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição do Pedido')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='controle_pedidos/NFE', verbose_name='Nota Fiscal Eletronica')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Pedido Realizado Em')),
                ('status', models.SmallIntegerField(choices=[(1, 'Gerado'), (2, 'Enviado'), (3, 'Concluído')], default=1, verbose_name='Status')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='controle_estoque.fornecedor')),
                ('produtos', models.ManyToManyField(to='controle_pedidos.PedidoItem')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedido',
            },
        ),
    ]
