# Generated by Django 3.1.7 on 2021-04-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_auto_20210402_1427'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhopedido',
            name='pedidocompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_pedidos.pedidocompra'),
        ),
        migrations.AlterField(
            model_name='carrinhopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.produto'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_criadopor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='controle_estoque.fornecedor'),
        ),
    ]
