# Generated by Django 3.1.7 on 2021-04-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0004_auto_20210405_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'ordering': ['-id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
