# Generated by Django 3.1.7 on 2021-05-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0005_auto_20210409_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Gerado'), (2, 'Em separação'), (3, 'Enviado'), (4, 'Mecadoria Recebida'), (5, 'Concluído'), (6, 'Cancelado')], default=1, verbose_name='Status'),
        ),
    ]
