# Generated by Django 3.1.7 on 2021-04-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_empresa',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='historicoatualizacaoprecos',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hist_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicoatualizacaoprecos',
            name='criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='hist_preco_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicoatualizacaoprecos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hist_preco_produto', to='controle_estoque.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produto_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='produto_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ean',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='subcategoria',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
