# Generated by Django 3.1.7 on 2021-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_auto_20210311_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
