# Generated by Django 3.1.7 on 2021-04-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0003_produto_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
