# Generated by Django 3.1.7 on 2021-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0006_fornecedor_faturamento_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
