# Generated by Django 3.1.7 on 2021-04-20 00:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_estoque', '0001_initial'),
        ('controle_usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição da Venda')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pendente'), (2, 'Cancelada'), (3, 'Concluída')], default=1, verbose_name='Status')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='controle_pedidos/NFE', verbose_name='Nota Fiscal Eletronica')),
                ('cpf', models.CharField(help_text='Preencha o campo apenas com números.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11,11}$', message='Por favor, não insira letras, " . " e " - " no campo abaixo.')], verbose_name='CPF')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, help_text='Digite o valor de desconto da venda, exemplo R$ 10,00', max_digits=12, verbose_name='Desconto')),
                ('forma_pagto', models.SmallIntegerField(choices=[(1, 'Debito'), (2, 'Credito'), (3, 'Dinheiro'), (4, 'PicPay'), (5, 'Pix')], verbose_name='Forma De Pagamento')),
                ('valor_total_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total da Venda')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Venda Realizada Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venda_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('caixa', models.ForeignKey(help_text='Caixa que está efetuando a venda', on_delete=django.db.models.deletion.PROTECT, related_name='venda_caixa', to='controle_usuarios.funcionario', verbose_name='Operador/Caixa')),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='venda_criadopor', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(help_text='Vendedor que atendeu o cliente', on_delete=django.db.models.deletion.PROTECT, related_name='venda_vendedor', to='controle_usuarios.funcionario', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarrinhoVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_vendas.venda')),
            ],
        ),
    ]
