# Generated by Django 3.1.7 on 2021-03-24 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_usuarios', '0001_initial'),
        ('controle_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venda_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='caixa',
            field=models.ForeignKey(help_text='Caixa que está efetuando a venda', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venda_caixa', to='controle_usuarios.funcionario', verbose_name='Operador/Caixa'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venda_criadopor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(help_text='Vendedor que atendeu o cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venda_vendedor', to='controle_usuarios.funcionario', verbose_name='Vendedor'),
        ),
        migrations.DeleteModel(
            name='HistoricoVendas',
        ),
    ]
