# Generated by Django 3.1.7 on 2021-04-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_auto_20210402_1427'),
        ('controle_usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_vendas', '0002_auto_20210324_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhovenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.produto'),
        ),
        migrations.AlterField(
            model_name='carrinhovenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_vendas.venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venda_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='caixa',
            field=models.ForeignKey(help_text='Caixa que está efetuando a venda', on_delete=django.db.models.deletion.PROTECT, related_name='venda_caixa', to='controle_usuarios.funcionario', verbose_name='Operador/Caixa'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='venda_criadopor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(help_text='Vendedor que atendeu o cliente', on_delete=django.db.models.deletion.PROTECT, related_name='venda_vendedor', to='controle_usuarios.funcionario', verbose_name='Vendedor'),
        ),
    ]
