# Generated by Django 3.1.7 on 2021-04-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vendas', '0005_auto_20210405_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-id'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
