# Generated by Django 3.1.7 on 2021-05-13 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vendas', '0006_auto_20210409_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cpf',
            field=models.CharField(blank=True, help_text='Preencha o campo apenas com números.', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11,11}$', message='Por favor, não insira letras, " . " e " - " no campo abaixo.')], verbose_name='CPF'),
        ),
    ]
